line-length = 120

[lint]

select = [
    "A",     # flake8-builtins
    "ASYNC", # flake8-async
    "ARG",   # flake8-unused-arguments
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "T20",   # flake8-print
    "Q",     # flake8-quotes
    "I",     # isort
    "N",     # pep8-naming
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "F",     # pyflakes
    "FBT",   # flake8-boolean-trap
    "T20",   # flake8-print
    "RSE",   # flake8-raise
]

[lint.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "pydantic.field_validator",
]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[lint.isort]
split-on-trailing-comma = true
force-wrap-aliases = true
combine-as-imports = true
lines-after-imports = 2


[format]
quote-style = "single"
skip-magic-trailing-comma = false
